parameters:
#    blog.example.class: site1\BlogBundle\Example

services:
    site1_blog.antispam:
        class: site1\BlogBundle\Antispam\Antispam
        arguments: [@mailer, %locale%, 3]

    blog.validator.antiflood:                             # Le nom du service
        class: site1\BlogBundle\Validator\AntiFloodValidator   # La classe du service, ici notre validateur déjà créé
        arguments: [@request, @doctrine.orm.entity_manager]  # Les données qu'on injecte au service =  la requête et l'EntityManager
        scope: request                                       # Comme on injecte la requête, on doit préciser ce scope
        tags:
            - { name: validator.constraint_validator, alias: blog_antiflood }  # C'est avec l'alias qu'on retrouvera le service