parameters:
#    test1page1.example.class: test1\page1Bundle\Example

services:
#    test1page1.example:
#        class: %test1page1.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
